name: Docker Series Builds

on: 
  push: 
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout rep
        uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: docker build
        run: docker build -t CryptoLoM/python C:\Users\admin\docker-python\docker>
      - name: push image docker 
        run: docker push CryptoLoM/python
      - name: run test in docker container
        run: docker run CryptoLoM/python
